import Head from 'next/head'
import NextLink from 'next/link'
import PostCard from '../components/card/PostCard'
import { Box, Text, SimpleGrid, Button } from '@chakra-ui/react'
import { AddIcon } from '@chakra-ui/icons'

// react query
import { useQuery } from '@tanstack/react-query'

// api
import { getPosts } from '../api/postsApi'
import Loading from '../components/loading/Loading'

const Posts = () => {

    const {
        isLoading,
        isError,
        error,
        data: posts
    } = useQuery(['posts'], getPosts, {
        select: data => data.sort((a, b) => b.id - a.id)
    })

    let content
    if (isLoading) {
        content = <Loading />
    } else if (isError) {
        content = <p>{error.message}</p>
    } else {
        content = posts.map(post => {
            return (
                <PostCard key={post.id} postDetails={post} />
            )
        })
    }

    return (
        <>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by Informatika Media Pratama" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box padding={5}>
                <Box
                    mb={10}
                    display={'flex'}
                    alignItems={'center'}
                    justifyContent={'space-between'}
                >
                    <Text fontSize={'3xl'}>All Posts</Text>
                    <NextLink href='/posts/create'>
                        <Button
                            leftIcon={<AddIcon />}
                            colorScheme='green' variant='solid'
                        >
                            Post
                        </Button>
                    </NextLink>
                </Box>
                <SimpleGrid columns={[2, null, 3]} spacing='20px'>
                    {content}
                </SimpleGrid>
            </Box>
        </>
    )
}

export default Posts