import Head from 'next/head'
import Posts from './posts'

export default function Home() {
  return (
    <>
      <Head>
        <title>IMP</title>
        <meta name="description" content="Generated by Informatika Media Pratama" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Posts />
    </>
  )
}
